name: Build Application

on: push

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2.3.4
      - name: Print Current Directory
        run: pwd
      - name: List Files in Directory
        run: ls      
      - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '5.0.100-preview.2.20176.6'
      - name: Get DotNet Info
          run: dotnet --info
      - name: Check Dotnet CLi
        run: dotnet build
      - name: List Files in Directory
        run: ls TrickingLibrary.Api/ -R
      - name: Check NPM CLi
        run: npm -v

