name: Build Application

on: push

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2.3.4
      - name: Print Current Directory
        run: pwd
      - name: List Files in Directory
        run: ls
      - name: Get DotNet Info
        run: dotnet --info
      - name: Add dotnet v5 Signing Key
        run: wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
          dpkg -i packages-microsoft-prod.deb
      - name: Install dotnet v5 SDK
        run: sudo apt-get update; \
          sudo apt-get install -y apt-transport-https && \
          sudo apt-get update && \
          sudo apt-get install -y dotnet-sdk-5.0
      - name: Check Dotnet CLi
        run: dotnet build
      - name: List Files in Directory
        run: ls TrickingLibrary.Api/ -R
      - name: Check NPM CLi
        run: npm -v

