name: Build Application

on: push

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2.3.4
      - name: Print current directory
        run: pwd
      - name: List files in driectory
        run: ls
      - name: Check Dotnet CLi
        run: dotnet build
      - name: List Files in Directory
        run: ls TrickingLibrary.Api/ -R
      - name: Check NPM CLi
        run: npm -v

